name: API QA Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Smoke Tests
        run: |
          npx newman run "Smoke test.postman_collection.json" \
            --env-var "baseURL=https://jsonplaceholder.typicode.com" \
            -r htmlextra \
            --reporter-htmlextra-export reports/smoke-report.html

      - name: Upload Smoke Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-report
          path: reports/smoke-report.html

  regression-tests:
    name: Regression Tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Regression Tests
        run: |
          npx newman run "Regression test.postman_collection.json" \
            --env-var "baseURL=https://jsonplaceholder.typicode.com" \
            -r htmlextra \
            --reporter-htmlextra-export reports/regression-report.html

      - name: Upload Regression Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-test-report
          path: reports/regression-report.html
